"""Add Reservation model

Revision ID: 5a2160b12523
Revises: 8907e2caa451
Create Date: 2024-11-17 12:39:46.006437

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5a2160b12523'
down_revision = '8907e2caa451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('from_reserve', sa.DateTime(), nullable=True),
                    sa.Column('to_reserve', sa.DateTime(), nullable=True),
                    sa.Column('meetingroom_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['meetingroom_id'],
                                            ['meetingroom.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    # ### end Alembic commands ###
