"""Add description to MeetingRoom

Revision ID: 77d5e3d513f9
Revises: c7e654d1e3a2
Create Date: 2024-10-31 08:16:31.173309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d5e3d513f9'
down_revision = 'c7e654d1e3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingroom', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetingroom', 'description')
    # ### end Alembic commands ###
